### ISSUE TITLE
Unable to find CSLA assembly 

### ISSUE THREAD

**Issue by rizdplex** [MarimerLLC/cslaforum#303]
Hi,
We have an ASP.NET web application which uses CSLA framework (Version - 2.1.4.0) for managing Business objects, data sources, network protocol, enterprise-level application consistency and security. Our application uses the same version of CSLA (Version - 2.1.4.0) from last couple of years and in past we didn’t face any issues with this CSLA. 
Recently on production server our application started throwing below exception which seems like an exception encountered due to CSLA. This issue has been encountered hundreds of time within second on production server which makes CPU usage reach to almost 100%. This 100% CPU usage causes unresponsiveness for the SQL queries from SQL server. We are not sure why this CSLA exceptions (hundreds of time within second) have impacted on SQL server which makes SQL server unresponsive. This issue resolves when we reset “SQL Server” service on production server.
 
**Note - We have physically separate production environment for application server and database server and during above scenario the application server CPU usages reaches to almost 100% while Database Server CPU usage was normal. But Still SQL Server hosted on Database server was unresponsive while occurring this CSLA error on Application Server.**

Below is the CSLA exception encountered on Application Server:-
 
An unhandled exception occurred and the process was terminated.
Application ID: DefaultDomain
Process ID: 7700
Exception: System.Runtime.Serialization.SerializationException
Message: Unable to find assembly 'Csla, Version=2.1.4.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30'.
StackTrace:    at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObject(MemoryStream stm)
   at System.AppDomain.Deserialize(Byte[] blob)
   at System.AppDomain.UnmarshalObject(Byte[] blob)

Regarding this exception we referred blogs on CSLA.NET forum and as per these blogs, it is a bug/feature of .NET where deserialization is unable to find an already loaded assembly in memory.
These blogs also provided the information about the workaround to handle this exception and also mentioned that this workaround is already implemented in CSLA library. We confirmed this by looked in the CSLA library used by our application and noticed that this workaround already implemented in CSLA library which used by our application. 
But still our application throwing same exception which makes site unresponsive.

We also try to debug Serialization Workaround code to check whether it is working correctly or not but since we are not able to reproduce this issue on our development environment so we can't able to debug it.  

Can you please provide suggestion on when and why this issue is encountering on our production environment and why it did not handled by Serialization Workaround which is already implemented in CSLA library present within our application?

Is there anything that we miss out which raise this exception continuously?

Please review and help us to identify cause of issue so that we can handle it within our application.

**Comment by rockfordlhotka** [comment]
Clearly something changed in your production environment - a patch to Windows or .NET or something - that changed the behavior in some way.

It is true that when .NET code is running in some containers (such as IE or COM+) the serialization workaround is required due to a 'feature' of .NET. The serialization workaround is _not_ normally active just because you are using CSLA - it is something you need to set up within your container.
