### ISSUE TITLE
ProjectTracker.Ui.Xamarin.Android cannot load System.Configuration

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/cslaforum#542]
I'm trying to build the current ProjectTracker sample and getting the following error:

Exception while loading assemblies:
System.IO.FileNotFoundException:
**Could not load assembly**
'**System.Configuration**,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Perhaps it doesn't exist in the Mono for Android profile?**

File name: 'System.Configuration.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	ProjectTracker.Ui.Xamarin.Android

**Comment by rockfordlhotka** [comment]
This is with CSLA 4.7.100?

**Comment by michaelcsikos** [comment]
4.7.101

**Comment by rockfordlhotka** [comment]
The solution is to change one line of code in the DAL project (believe it or not!). I _think_ this happens because the Xamarin linker is trying to resolve all dependencies to eliminate code that isn't needed on the client, so it is looking at code that the client would never try to actually load at runtime - specifically, at the DAL project, which is _referenced_ but never instantiated.

In the `DalFactory.cs` file change the `using` statement from `System.Configuration` to a CSLA namespace:

```
using Csla.Configuration;
```

I've done this in a pending PR, but if you want to move forward right now this is the solution.

**Comment by michaelcsikos** [comment]
Thanks, Rocky.
