### ISSUE TITLE
Can't log in to ProjectTracker via ptrackerserver.azurewebsites.net

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/cslaforum#554]
**Describe the bug**
I've set the WinForms App.config to
"CslaDataPortalUrl" value="http://ptrackerserver.azurewebsites.net/WcfMobilePortal.svc"

**Version and Platform**
CSLA version: 4.7.200
OS: Windows
Platform: WinForms

**Code that Fails**
Using admin/admin or manager/manager to log in throws the following exception.

**Stack Trace or Exception Detail**
System.InvalidOperationException
  HResult=0x80131509
  Message=SerializationInfo.GetValue: count
  Source=Csla
  StackTrace:
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object criteria)
   at ProjectTracker.Library.Security.PTIdentity.GetPTIdentity(String username, String password) in D:\Temp\csla-master\Samples\ProjectTracker\ProjectTracker.BusinessLibrary.Shared\Security\PTIdentity.cs:line 25
   at ProjectTracker.Library.Security.PTPrincipal.Login(String username, String password) in D:\Temp\csla-master\Samples\ProjectTracker\ProjectTracker.BusinessLibrary.Shared\Security\PTPrincipal.cs:line 33
   at PTWin.LoginForm.OK_Click(Object sender, EventArgs e) in D:\Temp\csla-master\Samples\ProjectTracker\ProjectTracker.Ui.WinForms\LoginForm.cs:line 23
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.TextBoxBase.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at PTWin.MainForm.DoLogin() in D:\Temp\csla-master\Samples\ProjectTracker\ProjectTracker.Ui.WinForms\MainForm.cs:line 330
   at PTWin.MainForm.<MainForm_Load>d__4.MoveNext() in D:\Temp\csla-master\Samples\ProjectTracker\ProjectTracker.Ui.WinForms\MainForm.cs:line 39

Inner Exception 1:
KeyNotFoundException: The given key was not present in the dictionary.

**Am I missing something?**

**Comment by rockfordlhotka** [comment]
That Azure endpoint is what I use "for real", as much "real" as there is with a demo project 😄 

The thing is, I use it as I'm building out the next version of CSLA, and when doing live demos at conferences.

In this case I think it is either a touch ahead or behind current (I don't remember which). One of the changes coming in version 4.7.200 is removing the dependency on DataContractSerializer - necessary to support Blazor - and that meant changing how `MobileList` is serialized.

I expect the versions to come back into sync in the next few days.

In any case, you can always switch the client app's config file to use localhost instead of my Azure endpoint. Or create and use your own Azure endpoint (just deploy the app server project to Azure).
