### ISSUE TITLE
Issue with HttpProxy

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/cslaforum#612]
**Describe the bug**
We have a custom data portal proxy factory and data portal proxy, which implements our retry/failover logic in the event the remote data portal call fails.  We have different URLs (in production, via multiple DNS entries) to use if a data portal call fails.  We subclass HttpProxy as well so that we can set a larger Timeout value.

I've hit an issue since updating to Csla 4.7.200 which I believe is caused due to the HttpProxy now keeping a static reference to the HttpClient.  I understand this is desired, but with the way out failover logic works (which is to keep a list of proxies to try, in order), the HttpProxy fails when it tries to set the Timeout AFTER making the initial call as it seems some properties on HttpClient cannot be changed once the first request is made.

The classes to look at are in the Business.Client-NS20 project in the DataPortalProxy folder.  The FailoverDataPortalProxy factory builds two instances of the IncreatedTimeoutHttyProxy, the first one has an invalid URL (which causes a 404); the second call should work, but since Timeout is set a second time, it fails.

**Version and Platform**
CSLA version: 4.7.200
OS: Windows
Platform: WinForms, Xamarin (probably all which support HttpProxy)

**Code that Fails**
https://github.com/ajj7060/HttpProxyError

**Stack Trace or Exception Detail**
System.InvalidOperationException:  This instance has already started one or more requests. Properties can only be modified before sending the first request.

   at Csla.DataPortalClient.HttpProxy.<Fetch>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Business.DataPortalProxy.FailoverPortalProxy.<Fetch>d__3.MoveNext()

**Comment by ajj7060** [comment]
@rockfordlhotka I created a pull request which should fix this issue.  Also, I discovered that this seems to happen if you use anything but the default timeout for HttpProxy, so it actually has nothing to do with our failover code.

The pull request is here:  https://github.com/MarimerLLC/csla/pull/916
