### ISSUE TITLE
CslaFastStart throws exception

### ISSUE THREAD

**Issue by timbered** [MarimerLLC/cslaforum#620]
Greetings! I am totally new to CSLA, and am anxious to get started. So, I downloaded it, and went first to the CslaFastStart example and built it on Visual Studio 2017. With no changes, when I run it, it blows up when deleting an existing name. From what I can tell, the lookup of the Id number is failing in PersonDal.cs GetPerson.

Note that this happens when I build the example in VS 2017. I tried it in 2015 I did not get the same error. I did get exceptions thrown from the DLL when the run exited, but at least it executed to completion.

So, what am I missing?

CSLA version: 4.7.200
OS: Windows, 10x64, Visual Studio 2017

System.Exception
  HResult=0x80131500
  Message=Index not found
  Source=DataAccessLayer
  StackTrace:
   at DataAccessLayer.PersonDal.GetPerson(Int32 id) in C:\Users\user\Desktop\csla-master_New\csla-master\Samples\CslaFastStart\DataAccessLayer\PersonDal.cs:line 21
   at BusinessLayer.PersonEdit.DataPortal_Fetch(Int32 id) in C:\Users\user\Desktop\csla-master_New\csla-master\Samples\CslaFastStart\BusinessLayer\PersonEdit.cs:line 50
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)

**Comment by timbered** [comment]
Hummm...Upon further debugging, it's an error in the CslaFastStart logic, not a Csla bug.

The example deletes the person, then does a try..catch to see if it's deleted by trying to read it. When the read attempt fails within the GetPerson, it throws the exception because it's been deleted (doh!).

As to why I thought it worked in 2015 and not 2017, I'm going to chalk it up to having stared at this thing for several hours and internal brain confusion. Apologies.

Anyway, at least I know what's wrong. However, might I suggest a fix for the example in a future release? As I said, this is my fist attempt at anything Csla-related, and it was an unnecessary distraction.

Thanks!
