### ISSUE TITLE
serialization exception when trying to clone or save a business object

### ISSUE THREAD

**Issue by philadefenderrob** [MarimerLLC/cslaforum#713]
I'm using CSLA 4.3.13 and am encountering a serialization exception when I try to save a  business object with lists in it. I've read as much as I could find about this and tried cloning the object first as suggested in one of the posts, but the exception is then thrown on the clone statement. Here's a snippet of code (MatterItemTriggers is a list in _VOP):

                    Try
                        _VOP.MatterItemTriggers.Clear()
                        Dim clonedBO As VOPItem
                        clonedBO = _VOP.Clone
                        clonedBO.ApplyEdit()
                        _VOP = clonedBO.Save()
                    Catch ex As Exception
                        Debug.WriteLine(ex.Message)
                    End Try

Interestingly, the exception isn't thrown unless I step through the code. Any guidance would be well appreciated. Thanks.

Here's a stack trace of the exception (I think this was the trace before I incorporated cloning of the BO, was just saving) :

System.Runtime.Serialization.SerializationException was caught
  HResult=-2146233076
  Message=Type 'Csla.Data.SafeDataReader' in Assembly 'Csla, Version=4.3.13.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' is not marked as serializable.
  Source=mscorlib
  StackTrace:
       at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
       at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
       at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, SerializationBinder binder)
       at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
       at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
       at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
       at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
       at Csla.Serialization.BinaryFormatterWrapper.Serialize(Stream serializationStream, Object graph)
       at Csla.Core.ObjectCloner.Clone(Object obj)
       at Csla.Core.BusinessBase.GetClone()
       at Csla.Core.BusinessBase.System.ICloneable.Clone()
       at Csla.DataPortal.Update[T](T obj)
       at Csla.BusinessBase`1.Save()

**Comment by rockfordlhotka** [comment]
It sounds like you have a field that references a SafeDataReader.

**Comment by philadefenderrob** [comment]
Thanks for your quick response, Rocky. Couldn't find any fields which were referencing a SafeDataReader, but your comment provoked me to investigate use of the SafeDataReader in a new BO. Turns out I had forgotten to create a method in the new BO for mapping database values to properties, making use of the SafeDataReader. Not sure why this manifested in a SerializationException. Thanks for your insight.
