### ISSUE TITLE
Null Ref Exception fetching/updating business object not derived from IDataPortalTarget

### ISSUE THREAD

**Issue by oatsoda** [MarimerLLC/cslaforum#721]
**Describe the bug**

Exception fetching/updating business object not derived from IDataPortalTarget

**Version and Platform**
CSLA version: 4.10.0
OS: Windows
Platform: WinForms

**Code that Fails**

Any fetch of a non-derived object.

**Stack Trace or Exception Detail**

    at System.Object.GetType()
    at Csla.Reflection.MethodCaller.GetCachedMethod(Object obj, String method, Boolean hasParameters, Object[] parameters) in C:\src\rdl\csla\Source\Csla.Shared\Reflection\MethodCaller.cs:line 98
    at Csla.Reflection.MethodCaller.IsAsyncMethod(Object obj, String method, Boolean hasParameters, Object[] parameters) in C:\src\rdl\csla\Source\Csla.Shared\Reflection\MethodCaller.cs:line 1144
    at Csla.Utilities.ThrowIfAsyncMethodOnSyncClient(Boolean isSync, Object obj, String methodName, Object[] parameters) in C:\src\rdl\csla\Source\Csla.Shared\Utilities.cs:line 415
    at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext() in C:\src\rdl\csla\Source\Csla.Shared\Server\SimpleDataPortal.cs:line 159
    at Csla.DataPortal`1.Fetch(Type objectType, Object criteria) in C:\src\rdl\csla\Source\Csla.Shared\DataPortalT.cs:line 439
    at Csla.DataPortal`1.Fetch(Object criteria) in C:\src\rdl\csla\Source\Csla.Shared\DataPortalT.cs:line 424

Looks like `SimpleDataPortal` (`Fetch`, `Update` etc.) have an issue when `target` is not of type `IDataPortalTarget` - There are `null` checks but then the `ThrowIfAsyncMethodOnSyncClient` causes the Null Reference Exception further down then stack when `GetType()` is called on the now null object.

**Comment by oatsoda** [comment]
Perhaps should be passing in `obj.Instance` to the `Utilities.ThrowIfAsyncMethodOnSyncClient` method?

**Comment by oatsoda** [comment]
Culprit appears to be this: https://github.com/MarimerLLC/csla/commit/6268e39a296d4d0dd31a0e66187c8ec4a32c7c2f

**Comment by rockfordlhotka** [comment]
Agreed, I'll file this as a bug in the backlog.

**Comment by rockfordlhotka** [comment]
@oatsoda do you want to do a PR for this?

**Comment by oatsoda** [comment]
@rockfordlhotka Thanks. I will do. I've just come back onto our CSLA-based project (~1m LOC) and tried to upgrade from CSLA 4.6.400 - but the authors of some of the original code from c. 2009 have used a bunch of non-base classed BOs.

I can fix by adding the base class, but I then additionally have to hack them with `MarkOld()` and `MarkNew()` for Updates to work then!  There are about 100 of them to do and test!

Should/will CSLA support these going forward? Trying to decide whether to wait for the fix or just take the pain and testing to finally weed them all out now!

**Comment by oatsoda** [comment]
@rockfordlhotka https://github.com/MarimerLLC/csla/pull/1113
