### ISSUE TITLE
Csla/winrt Resource Contexts may not be created on threads that do not have a CoreWindow

### ISSUE THREAD

**Issue by AsadCheema** [MarimerLLC/cslaforum#75]
Created a BO, from WinRT app, when pull existing item it pulls ok, but when call async api to create new object, following error occurs and application crashes.

An exception of type 'System.Exception' occurred in Csla.DLL but was not handled in user code

Additional information: Resource Contexts may not be created on threads that do not have a CoreWindow. (Exception from HRESULT: 0x80073B27)

Regards.

**Comment by rockfordlhotka** [comment]
Thank you, I have logged this as a bug: https://github.com/MarimerLLC/csla/issues/464

**Comment by AsadCheema** [comment]
Thank you Rocky, is there any workaround for this issue. Since all our constructors are now public, so is it required server side data-portal to create object, or [RunLocal] should create object on client-side.
Regards.

**Comment by rockfordlhotka** [comment]
I believe the issue will occur when `[RunLocal]` is used as well, according to a similar bug report I have.

I don't know of a workaround - I'm trying now to create a failing test case for debugging.

**Comment by rockfordlhotka** [comment]
@AsadCheema , when you say "WinRT" are you on Win8.1 or Win10? Specifically, I'm finding that the problematic code is failing in UWP apps and is due to a change in the way UWP handles language resources vs WinRT.

**Comment by AsadCheema** [comment]
No, i am converting all my old Csla 3.5 dlls using new Csla 4.6 ver. while testing some of my BO on 8.1 client, i am facing this issue, My List/edit of existing Object was running fine, but when creating new Object was showing this error. I am putting the test case in separate project so any one can test if i am doing something wrong.

**Comment by rockfordlhotka** [comment]
Thank you, that is very helpful, as it confirms my suspicion that the problem exists in WinRT as well as UWP (but I don't have a Win8.1 machine on which to test).

I have a fix committed to GitHub at this point, and will push it to NuGet soon. There's one other issue I'm trying to fix before the NuGet push.

**Comment by rockfordlhotka** [comment]
The fix is in NuGet now (v4.6.175-Beta prerelease)
https://github.com/MarimerLLC/csla/releases/tag/v4.6.175-Beta

**Comment by AsadCheema** [comment]
An exception of type 'System.TypeLoadException' occurred in TstUnvApp81.Windows.exe but was not handled in user code

Additional information: Type 'Csla.Core.BusinessBase' in assembly 'Csla, Version=4.6.175.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the serialization attribute that it is decorated with.

**Comment by rockfordlhotka** [comment]
At least that's a new error.

When exactly does this error occur?

**Comment by AsadCheema** [comment]
this error occurred in button press method even before calling BO's async method.
    private void pullItemDtl_Click(object sender, RoutedEventArgs e)
    {
      PullItemDtlData();
    }

    private async void PullItemDtlData()
    {
      try
      {
        var nItm = await e2.SOM.Lib.ItemDtl.NewItemDtlAsync();
        //this.DataContext = nItm;

      }
      catch (Exception ex)
      {
        this.DataContext = null;
      }
      finally
      {
        //ProgressDisplay.IsActive = false;
      }
    }

**Comment by AsadCheema** [comment]
i don't know calling  PullItemDtlData(); method in button_press event has something to do with CSLA

**Comment by rockfordlhotka** [comment]
Is this with a remote data portal?

**Comment by AsadCheema** [comment]
yes, using MobilePortal with WcfAppServer in Windows 8.1 Desktop Client

**Comment by AsadCheema** [comment]
in app.xaml.cs i have folowing settings
#if WINDOWS_PHONE_APP
      Csla.ApplicationContext.DataPortalProxy = typeof(Csla.DataPortalClient.LocalProxy).AssemblyQualifiedName;
      Csla.ApplicationContext.DataPortalUrlString = @"http://localhost/WcfAppServer/MobilePortal.svc";
#else
      Csla.ApplicationContext.DataPortalProxy = typeof(Csla.DataPortalClient.WcfProxy).AssemblyQualifiedName;
      Csla.ApplicationContext.DataPortalUrlString = @"http://localhost/WcfAppServer/MobilePortal.svc";
#endif

**Comment by rockfordlhotka** [comment]
Can you provide the entire stack trace for the error (`ex.ToString()`)? At the moment I am unable to replicate your issue, and it would help to see which serializer is throwing the exception.

**Comment by AsadCheema** [comment]
how to do that, there is <Copy exception to clipboard> option rendered as follows:
System.TypeLoadException was unhandled by user code
  HResult=-2146233054
  Message=Type 'Csla.Core.BusinessBase' in assembly 'Csla, Version=4.6.175.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the serialization attribute that it is decorated with.
  Source=TstUnvApp81.Windows
  TypeName=Csla.Core.BusinessBase
  StackTrace:
       at TstUnvApp81.MainPage.PullItemDtlData()
       at TstUnvApp81.MainPage.pullItemDtl_Click(Object sender, RoutedEventArgs e)
  InnerException:

**Comment by rockfordlhotka** [comment]
if you have access to the exception object (in your `catch` block) you can use the Immediate window to do this:

```
? ex.ToString()
```

**Comment by AsadCheema** [comment]
i put method cal in try-catch block and in catch doing ex.ToString()
try
      {
        PullItemDtlData();
      }
      catch(Exception ex)
      {
        string err = ex.Message;
      }
System.TypeLoadException: Type 'Csla.Core.BusinessBase' in assembly 'Csla, Version=4.6.175.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the serialization attribute that it is decorated with.
   at TstUnvApp81.MainPage.PullItemDtlData()
   at TstUnvApp81.MainPage.pullItemDtl_Click(Object sender, RoutedEventArgs e)

**Comment by rockfordlhotka** [comment]
Hmm, I would have expected more detail. OK, that makes things more challenging.

**Comment by AsadCheema** [comment]
ok, let me reference the csla dll from csla-4.6.175 project, and if my code jump into csla classes, then let me check where it is bursting out....

**Comment by rockfordlhotka** [comment]
Thank you

**Comment by AsadCheema** [comment]
ok, i think since my PullItemDtlData() method is local method, even stepping-in should take in in-side the same cs file method, so it  won't take me to Csla source code, don't know how cum Csla.dll related error occurred at this level,

**Comment by rockfordlhotka** [comment]
Can you try manually doing a clone of your object?

```csharp
obj = Csla.Core.ObjectCloner.Clone(obj);
```

That'll trigger serialization/deserialization, and therefore should cause the exception to occur.

**Comment by AsadCheema** [comment]
the activity was to generate one Object, In my Xaml page this method is in code behind page.xaml.cs file binded with one button on GUI.

1.private void pullItemDtl_Click(object sender, RoutedEventArgs e)
2. {
3.     PullItemDtlData();
4. }

and once i press the button on GUI above method executed and try to run PullItemDtlData() method (line 3) defined with async preifix, as follows 

5.private async void PullItemDtlData()
6.  {
7.     try
8.      {
9.        var nItm = await e2.SOM.Lib.ItemDtl.NewItemDtlAsync();
10.       //this.DataContext = nItm;
11.    }
12.    catch (Exception ex)
13.    {
14.      this.DataContext = null;
15.    }
16.    finally
17.    {
18.      //ProgressDisplay.IsActive = false;
19.    }
    }

which suppose to pull data via remote data portal (Line 9). Now even reaching line 9, i am getting exception on line 3 PullItemDtlData(); which seems to me very strange that i am unable to call my next local method generating following error

System.TypeLoadException was unhandled by user code
  HResult=-2146233054
  Message=Type 'Csla.Core.BusinessBase' in assembly 'Csla, Version=4.6.175.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the serialization attribute that it is decorated with.
  Source=TstUnvApp81.Windows
  TypeName=Csla.Core.BusinessBase
  StackTrace:
       at TstUnvApp81.MainPage.PullItemDtlData()
       at TstUnvApp81.MainPage.pullItemDtl_Click(Object sender, RoutedEventArgs e)
  InnerException: 

Since i do not have any Obj in my hand, so how cum execute 

obj = Csla.Core.ObjectCloner.Clone(obj);

Regards.

**Comment by dazinator** [comment]
I am also seeing this same exception when referencing the CSLA assembly that's compiled as a PCL assembly, from a .NET 4.5 project, and then using business objects that are also in a PCL project, compiled against the same CSLA PCL assembly. See #526
