### ISSUE TITLE
SafeDataReader  throws System.IO.FileLoadException

### ISSUE THREAD

**Issue by EricNgo1972** [MarimerLLC/cslaforum#794]
**Describe the bug**
Creating a new SafeDataReader throws a System.IO.FileLoadException: 
System.IO.FileLoadException: 'Could not load file or assembly 'System.Data.SqlClient, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

**Version and Platform**
CSLA Xamarin Forms version: 4.11.2 (Latest version from Nuget). .Net Standard 2.03
OS: Windows 10.
Platform: Xamarin, Windows Console.

**Code that Fails**
 var dr = new SafeDataReader(cm.ExecuteReader());

**Stack Trace or Exception Detail**
   at Csla.Data.SafeDataReader..ctor(IDataReader dataReader)
   at SPC.BO.DM.DOCInfoList.DataPortal_Fetch(QueryCriteria criteria) in C:\Business Solutions\Mobile\LeaveApp\SPC.CORE\Shared Functions\DocLink\DOCInfoList.cs:line 138
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)

**Additional context**
If I use only IDataReader only. everything works, and I can read data from the SQL database just fine.
But I need the null data converter feature from SafeDataReader.

**Comment by rockfordlhotka** [comment]
I suspect this is related to Microsoft's shift from System.Data.SqlClient to Microsoft.Data.SqlClient, though I'm not sure.

We are addressing this issue in version 5: https://github.com/MarimerLLC/csla/issues/981

I'm not sure there's a workaround in v4.11.

**Comment by rockfordlhotka** [comment]
Actually I suppose one workaround is to copy the `SafeDataReader` code into your project (in a different namespace) where it should work because it is relying on the references in your project.

That should be a temporary workaround until you can move to v5 where the issue should be resolved.

**Comment by EricNgo1972** [comment]
Thank you for your suggestion. 
I've moved the SafeDataReader to our code and resolved this problem.
