### ISSUE TITLE
Csla 5.1.0 Serialization of type object not supported

### ISSUE THREAD

**Issue by JacoJordaan** [MarimerLLC/cslaforum#899]
**Question**
Was there any possible changes from version 4.11 to 5.1 that can cause a Serialization of type object not supported exception where it previously was not an issue?
And at what times will this exception be thrown?

I have converted a WPF project from version 4..11 to 5.1. In version 4.11 all was working well.
I have an Telerik grid control that binds to my business object. If I edit the specific cell in the grid the second time it throws this exception. I had to upgrade the Telerik controls as well, so this may also be causing the issue.

Unfortunately the stack trace does not help me much:
```
  StackTrace:
   at Csla.Serialization.Mobile.CslaBinaryWriter.Write(Object target, BinaryWriter writer)
   at Csla.Serialization.Mobile.CslaBinaryWriter.Write(Stream serializationStream, List`1 objectData)
   at Csla.Serialization.Mobile.MobileFormatter.Serialize(Stream serializationStream, Object graph)
   at Csla.Core.FieldManager.FieldDataManager.Csla.Core.IUndoableObject.CopyState(Int32 parentEditLevel, Boolean parentBindingEdit)
   at Csla.Core.UndoableBase.CopyState(Int32 parentEditLevel)
   at Csla.Core.BusinessBase.BeginEdit()
   at Csla.Core.BusinessBase.System.ComponentModel.IEditableObject.BeginEdit()
   at Telerik.Windows.Data.QueryableCollectionView.<>c.<BeginEditItem>b__64_0(IEditableObject i)
   at Telerik.Windows.Data.QueryableCollectionView.ExecuteAs[T](Object item, Action`1 action)
   at Telerik.Windows.Data.QueryableCollectionView.BeginEditItem(Object item)
   at Telerik.Windows.Data.QueryableCollectionView.EditItem(Object item)
   at Telerik.Windows.Data.DataItemCollection.EditItem(Object item)
   at Telerik.Windows.Controls.GridView.GridViewDataControl.set_RowInEditMode(GridViewRow value)
   at Telerik.Windows.Controls.GridView.GridViewRow.IsInEditModeChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
```

**Version and Platform**
CSLA version: 5.1.000
OS: Windows
Platform: WPF

**Comment by rockfordlhotka** [comment]
Can you get a ToString of the exception object?

**Comment by JacoJordaan** [comment]
@rockfordlhotka , here is the ToString of exception:
```
System.NotSupportedException: Serialization of type object is not supported.
   at Csla.Serialization.Mobile.CslaBinaryWriter.Write(Object target, BinaryWriter writer)
   at Csla.Serialization.Mobile.CslaBinaryWriter.Write(Stream serializationStream, List`1 objectData)
   at Csla.Serialization.Mobile.MobileFormatter.Serialize(Stream serializationStream, Object graph)
   at Csla.Core.FieldManager.FieldDataManager.Csla.Core.IUndoableObject.CopyState(Int32 parentEditLevel, Boolean parentBindingEdit)
   at Csla.Core.UndoableBase.CopyState(Int32 parentEditLevel)
   at Csla.Core.BusinessBase.BeginEdit()
   at Csla.Core.BusinessBase.System.ComponentModel.IEditableObject.BeginEdit()
   at Telerik.Windows.Data.QueryableCollectionView.<>c.<BeginEditItem>b__64_0(IEditableObject i)
   at Telerik.Windows.Data.QueryableCollectionView.ExecuteAs[T](Object item, Action`1 action)
   at Telerik.Windows.Data.QueryableCollectionView.BeginEditItem(Object item)
   at Telerik.Windows.Data.QueryableCollectionView.EditItem(Object item)
   at Telerik.Windows.Data.DataItemCollection.EditItem(Object item)
   at Telerik.Windows.Controls.GridView.GridViewDataControl.set_RowInEditMode(GridViewRow value)
   at Telerik.Windows.Controls.GridView.GridViewRow.IsInEditModeChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Telerik.Windows.Controls.GridView.GridViewRow.set_IsInEditMode(Boolean value)
   at Telerik.Windows.Controls.GridView.GridViewDataControl.OnCellEditModeChanged(GridViewCell cell, Boolean newIsInEditMode)
   at Telerik.Windows.Controls.GridView.GridViewCell.IsInEditModeChanged(DependencyObject target, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Telerik.Windows.Controls.GridView.GridViewCell.set_IsInEditMode(Boolean value)
   at Telerik.Windows.Controls.GridView.GridViewDataControl.SwitchCellToEditMode(GridViewCell cell)
   at Telerik.Windows.Controls.GridView.GridViewDataControl.BeginEdit(GridViewCell gridViewCell, RoutedEventArgs editEventArgs)
   at Telerik.Windows.Controls.GridView.GridViewDataControl.OnCellMouseDown(GridViewCell cell, MouseButtonEventArgs args)
   at Telerik.Windows.Controls.GridView.GridViewCell.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by rockfordlhotka** [comment]
Somewhere in your graph you have a reference to something of type `object`. Which, of course, you already knew. 😏

Are you on 4.11.0, .1, or .2?

I'm seeing some history around how statestack is handled in n-level undo around the time of 4.11.2.

**Comment by JacoJordaan** [comment]
I was on 4.11.0 when upgraded to 5.1.0.

I am sure it must be related to the changes in n-level undo. 

Any suggestions how I can go about to find the property(ies) causing the exception?
I am thinking of some tests with BeginEdit and ApplyEdit scenarios.

**Comment by rockfordlhotka** [comment]
I don't know of a better solution right now, though you can see that I've added a work item to improve that message text.

**Comment by JacoJordaan** [comment]
One of the properties on my object was of type ReadOnlyListBase. I had it marked as [NotUndoable]. This was working previously.

I have changed the object as BusinessListBase and it is working fine now.

Appreciate assistance.

**Comment by KC7465128305** [comment]
I have the same issue when I migrated from CSLA 4.10.0 to CSLA 5.1.0 and I have never used Telerik controls.  Also my project does not use any ReadOnlyListBase, only BusinessListBase.
